services:
  app:
    image: eclipse-temurin:21-jdk
    container_name: java_app
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "80:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/atark
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - db
    command: >
      sh -c "apt update && apt install -y maven && mvn clean package && java -jar target/*.jar"

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: atark
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
