@startuml
start
:Завантажити конфігурацію з файлу;
if (Файл існує?) then (так)
    :Прочитати конфігурацію;
else (ні)
    :Повідомити про помилку і вийти;
endif

repeat
    :Отримати дані спострежень з сенсору;
    :Створити JSON для передачі даних;
    :Надіслати HTTP-запит до API;
    if (Код відповіді OK?) then (так)
        :Повідомити про успіх;
    else (ні)
        :Повідомити про помилку;
    endif
    :Очікувати заданий інтервал;
repeat while (true)
@enduml

