@startuml
partition "Activity Diagram" {
  start
  :Користувач відкриває сторінку керування теплицею;
  :Система запитує дані сенсорів;
  :Сенсори відправляють дані;
  :Дані відображаються користувачу;
  if (Користувач бажає керувати контролерами?) then (Так)
    :Користувач вибирає дію (включити/вимкнути);
    :Команда передається на контролер;
    :Контролер виконує дію;
    :Оновлення стану відображається;
  else (Ні)
    :Очікування подальших дій;
  endif
  stop
}
@enduml
