@startuml
|User|
start
:Отримання показників сенсора;

:Перевірка даних на відповідність
до правил автоматизації;

if (Дані задовольняють правило?) then (так)
  :Виконання дії автоматизації;
  :Надсилання команди контролерам;
else (ні)
  :Очікування наступних показників;
endif

stop
@enduml
