@startuml
actor "Користувач" as User

frame "Підсистема 'Управління теплицями'" {
    usecase "Управляти теплицями" as UC1
    usecase "Встановлювати правила автоматизації" as UC2
    usecase "Встановлювати заплановані події" as UC21
    usecase "Встановлювати правила автоматизації, що залежать від показників середовища" as UC22
    usecase "Управляти контролерами у ручному режимі" as UC3

    User --> UC1
    User --> UC2
    User --> UC3

    UC2 .> UC21 : includes
    UC2 .> UC22 : includes
}

@enduml
